{% extends "base.html" %}

{% block title %}
Задача №{{task.task.id}}
{% endblock %}

{% block content %}

<div class="card text-center">
  <div class="card-header">
      {% if task.completed %}
    <h5 class="card-title">Завершена</h5>
      {% else %}
    <h5 class="card-title">Открытая</h5>
      {% endif %}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{task.task.headline}}</h5>
    <p class="card-text">{{task.task.text | wordwrap(5)}}</p>
      {% for file in task.task.files %}
        <a href="/tasks/{{task.task.id}}/{{file.id}}/download" class="card-link">{{file.name}}</a>
      {% endfor %}
  </div>
  <div class="card-footer text-body-secondary">
      {% if not task.completed %}
    <input type="submit" class="btn btn-primary" name="submit" onclick="completeFunction(task_id={{task.task.id}})" value="Подтвердить" />
      {% endif %}
  </div>
</div>

{% endblock %}
{% block script %}
<script>
        async function completeFunction(task_id) {
    event.preventDefault();  // Предотвращаем стандартное действие формы


    try {
        const response = await fetch('/tasks/'+task_id+'/complete', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
        });

        // Проверяем успешность ответа
        if (!response.ok) {
            // Получаем данные об ошибке
            const errorData = await response.json();
            displayErrors(errorData);  // Отображаем ошибки
            return;  // Прерываем выполнение функции
        }

        const result = await response.json();

        if (result.message) {  // Проверяем наличие сообщения о успешной регистрации
            window.location.href = task_id;  // Перенаправляем пользователя на страницу логина
        } else {
            alert(result.message || 'Неизвестная ошибка');
        }
    } catch (error) {
        console.error('Ошибка:', error);
        alert('Произошла ошибка. Пожалуйста, попробуйте снова.');
    }
}
    </script>

{% endblock %}

<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Задача №{{task.task.id}}</title>-->
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">-->
<!--</head>-->
<!--<body>-->

<!--<div class="card text-center">-->
<!--  <div class="card-header">-->
<!--    {{task.completed}}-->
<!--  </div>-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">{{task.task.headline}}</h5>-->
<!--    <p class="card-text">{{task.task.text}}</p>-->
<!--      {% for file in task.task.files %}-->
<!--        <a href="/tasks/{{task.task.id}}/{{file.id}}/download" class="card-link">{{file.name}}</a>-->
<!--      {% endfor %}-->
<!--    <a href="/pages/tasks/me" class="btn btn-secondary">Вернуться к списку</a>-->
<!--    <input type="submit" class="btn btn-primary" name="submit" onclick="completeFunction(task_id={{task.task.id}})" value="Подтвердить" />-->
<!--  </div>-->
<!--  <div class="card-footer text-body-secondary">-->
<!--  </div>-->
<!--</div>-->

<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>-->
<!--    <script>-->
<!--        async function completeFunction(task_id) {-->
<!--    event.preventDefault();  // Предотвращаем стандартное действие формы-->


<!--    try {-->
<!--        const response = await fetch('/tasks/'+task_id+'/complete', {-->
<!--            method: 'POST',-->
<!--            headers: {-->
<!--                'Content-Type': 'application/json'-->
<!--            },-->
<!--        });-->

<!--        // Проверяем успешность ответа-->
<!--        if (!response.ok) {-->
<!--            // Получаем данные об ошибке-->
<!--            const errorData = await response.json();-->
<!--            displayErrors(errorData);  // Отображаем ошибки-->
<!--            return;  // Прерываем выполнение функции-->
<!--        }-->

<!--        const result = await response.json();-->

<!--        if (result.message) {  // Проверяем наличие сообщения о успешной регистрации-->
<!--            window.location.href = task_id;  // Перенаправляем пользователя на страницу логина-->
<!--        } else {-->
<!--            alert(result.message || 'Неизвестная ошибка');-->
<!--        }-->
<!--    } catch (error) {-->
<!--        console.error('Ошибка:', error);-->
<!--        alert('Произошла ошибка. Пожалуйста, попробуйте снова.');-->
<!--    }-->
<!--}-->
<!--    </script>-->
<!--</body>-->
<!--</html>-->